# fly.toml app configuration file generated for goshop-backend on 2023-08-24T15:36:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goshop-backend"
primary_region = "lhr"

[build]

[deploy]
  
[env]
  FRONTEND_URL = "https://ecommerce-goshop.onrender.com"
  NODE_ENV = "prod"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
